project_id = "sdmusxkflouegqrmekpt"

[functions.send-request-status-email]
verify_jwt = false

[functions.razorpay-create-order]
verify_jwt = false

[functions.razorpay-verify-payment]
verify_jwt = false
